import {
  FaReact,
  FaNodeJs,
  FaDocker,
  FaGitAlt,
  FaGithub,
  FaJava,
} from 'react-icons/fa';

import {
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiPython,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiVuedotjs,
  SiAngular,
  SiNestjs,
  SiExpress,
  SiSpringboot,
  SiRedis,
  SiApachekafka,
  SiRabbitmq,
  SiFigma,
  SiVercel,
  SiRailway,
  SiGo,
  SiR,
  SiOctave,
  SiLinux,
  SiIntellijidea
} from 'react-icons/si';

export const technologies = [
    { name: 'React.js', size: 24, icon: FaReact, capacity: 95 },
    { name: 'Next.js', size: 20, icon: SiNextdotjs, capacity: 80 },
    { name: 'TypeScript', size: 22, icon: SiTypescript, capacity: 88 },
    { name: 'Tailwind', size: 18, icon: SiTailwindcss, capacity: 92 },
    { name: 'Node.js', size: 26, icon: FaNodeJs, capacity: 95 },
    { name: 'MongoDB', size: 19, icon: SiMongodb, capacity: 90 },
    { name: 'JavaScript', size: 28, icon: SiJavascript, capacity: 96 },
    { name: 'HTML', size: 21, icon: SiHtml5, capacity: 98 },
    { name: 'CSS', size: 23, icon: SiCss3, capacity: 94 },
    { name: 'Python', size: 25, icon: SiPython, capacity: 70 },
    { name: 'Git', size: 17, icon: FaGitAlt, capacity: 90 },
    { name: 'Docker', size: 20, icon: FaDocker, capacity: 78 },
    { name: 'Figma', size: 21, icon: SiFigma, capacity: 82 },
    { name: 'MySQL', size: 19, icon: SiMysql, capacity: 94 },
    { name: 'Postgres', size: 19, icon: SiPostgresql, capacity: 90 },
    { name: 'Vue', size: 22, icon: SiVuedotjs, capacity: 85 },
    { name: 'Angular', size: 21, icon: SiAngular, capacity: 72 },
    { name: 'NestJs', size: 18, icon: SiNestjs, capacity: 84 },
    { name: 'ExpressJs', size: 21, icon: SiExpress, capacity: 95 },
    { name: 'GoLang', size: 21, icon: SiGo, capacity: 90 },
    { name: 'Github', size: 22, icon: FaGithub, capacity: 92 },
    { name: 'Java', size: 22, icon: FaJava, capacity: 86 },
    { name: 'Springboot', size: 20, icon: SiSpringboot, capacity: 90 },
    { name: 'Railway', size: 22, icon: SiRailway, capacity: 80 },
    { name: 'Vercel', size: 19, icon: SiVercel, capacity: 70 },
    { name: 'Redis', size: 22, icon: SiRedis, capacity: 79 },
    { name: 'Kafka', size: 17, icon: SiApachekafka, capacity: 80 },
    { name: 'Rabbitmq', size: 21, icon: SiRabbitmq, capacity: 92 },
    { name: 'R', size: 18, icon: SiR, capacity: 79 },
    { name: 'Octave', size: 20, icon: SiOctave, capacity: 79 },
    { name: 'Linux', size: 22, icon: SiLinux, capacity: 75 },
];