
import {
  FaReact,
  FaNodeJs,
  FaDocker,
  FaGitAlt,
  FaGithub,
  FaJava,
} from 'react-icons/fa';

import {
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiPython,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiVuedotjs,
  SiAngular,
  SiNestjs,
  SiExpress,
  SiSpringboot,
  SiRedis,
  SiApachekafka,
  SiRabbitmq,
  SiFigma,
  SiVercel,
  SiRailway,
  SiGo,
  SiR,
  SiOctave,
  SiLinux,
  SiIntellijidea
} from 'react-icons/si';

export const technologies = [
    { name: 'React', size: 24, icon: FaReact },
    { name: 'Next.js', size: 20, icon: SiNextdotjs },
    { name: 'TypeScript', size: 22, icon: SiTypescript },
    { name: 'Tailwind', size: 18, icon: SiTailwindcss },
    { name: 'Node.js', size: 26, icon: FaNodeJs },
    { name: 'MongoDB', size: 19, icon: SiMongodb },
    { name: 'JavaScript', size: 28, icon: SiJavascript },
    { name: 'HTML', size: 21, icon: SiHtml5 },
    { name: 'CSS', size: 23, icon: SiCss3 },
    { name: 'Python', size: 25, icon: SiPython },
    { name: 'Git', size: 17, icon: FaGitAlt },
    { name: 'Docker', size: 20, icon: FaDocker },
    { name: 'Figma', size: 21, icon: SiFigma },
    { name: 'MySQL', size: 19, icon: SiMysql },
    { name: 'Postgres', size: 19, icon: SiPostgresql },
    { name: 'Vue', size: 22, icon: SiVuedotjs },
    { name: 'Angular', size: 21, icon: SiAngular },
    { name: 'NestJs', size: 18, icon: SiNestjs },
    { name: 'ExpressJs', size: 21, icon: SiExpress },
    { name: 'GoLang', size: 21, icon: SiGo },
    { name: 'Github', size: 22, icon: FaGithub },
    { name: 'Java', size: 22, icon: FaJava },
    { name: 'Springboot', size: 20, icon: SiSpringboot },
    { name: 'Railway', size: 22, icon: SiRailway },
    { name: 'Vercel', size: 19, icon: SiVercel },
    { name: 'Redis', size: 22, icon: SiRedis },
    { name: 'Kafka', size: 17, icon: SiApachekafka },
    { name: 'Rabbitmq', size: 21, icon: SiRabbitmq },
    { name: 'R', size: 18, icon: SiR },
    { name: 'Octave', size: 20, icon: SiOctave },
    { name: 'Linux', size: 22, icon: SiRabbitmq },
    { name: 'IntelliJ', size: 19, icon: SiIntellijidea },
  ];
